### ISSUE TITLE
Implement HTTPS certificate pinning

### ISSUE THREAD

**Issue by fredreichbier** [NetKnights-GmbH/privacyidea-ldap-proxy#27]
Right now, the certificate presented by privacyIDEA is checked against the OS certificate store. However, it would be good to be able to specify an actual certificate file in the INI file.

**Comment by cornelinux** [comment]
I would recommend the possibility to specify and additional CA certificate.
This way the admin who configures the HTTPS connection can decide:

* check HTTPS against OS certificate store. He would have to add the CA cert to the store
* check HTTPS against the local CA certificate
* do not check HTTPS

Thus: either running unsafe (do not check) or safe (check against CA, including Trust and Hostname!)

**Comment by fredreichbier** [comment]
The above commit implements (2) -- I'll see how we can implement (3) in the next days.

(2) is also very useful for the appliance: We can just tell the LDAP proxy to validate against whatever certificate privacyIDEA uses.
