### ISSUE TITLE
Review anonymous binds

### ISSUE THREAD

**Issue by fredreichbier** [NetKnights-GmbH/privacyidea-ldap-proxy#31]
We should check whether we want to forward anonymous binds to the LDAP backend. Right now, we are rejecting them.

**Comment by cornelinux** [comment]
It would be great, if we could configure, what to do with those binds.

(*) reject or
(  ) forward

**Comment by fredreichbier** [comment]
The branch references above makes handling of anonymous binds configurable. However, the LDAP standard doesn't even require that there is a bind request before any search requests are made (see [4.2.1 of RFC 2251](https://www.ietf.org/rfc/rfc2251.txt))
<pre>
   Unlike LDAP v2, the client need not send a Bind Request in the first
   PDU of the connection.  The client may request any operations and the
   server MUST treat these as unauthenticated. If the server requires
   that the client bind before browsing or modifying the directory, the
   server MAY reject a request other than binding, unbinding or an
   extended request with the "operationsError" result.
</pre>
But I'm not sure if the LDAP Proxy should even enforce that there is a bind request before any other operation.
