### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by kanthans** [NetKnights-GmbH/privacyidea-ldap-proxy#57]
Hi

Found this tool very useful to integrate with PrivacyIDEA and DS389 LDAP. Thank you :-)  

We have installed and ran this service as systemctl daemon. 

Can we have logging enabled so that it helps to troubleshoot. Right now to troubleshoot problems, we stop the service, run the twistd command and see the console messages to find the root cause. 

Is there anyway can we enable logging on this. 

Thank you once again for your great work

-SKN

**Comment by pablo-knight** [comment]
Hi,

look inside this file

https://github.com/NetKnights-GmbH/ubuntu/blob/master/deploy/privacyidea-ldap-proxy/privacyidea-ldap-proxy.service

you can create something like that to your service to get logging.

`StandardOutput=append:/var/log/privacyidea-ldap-proxy/privacyidea-ldap-proxy.log`
